//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class userRegistration
    {
        public int ID { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string CreateProfileFor { get; set; }
        public string DateOfBirth { get; set; }
        public string Height { get; set; }
        public string MaritalStatus { get; set; }
        public string MotherTongue { get; set; }
        public string Religion { get; set; }
        public string City { get; set; }
        public string PinCode { get; set; }
        public string MobileNumber { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string Gender { get; set; }
        public string ProfilePicture { get; set; }
        public string OTP { get; set; }
    }
}
